Repository DonutWare/Fladder, pull requests merged in 2024-10, with the labels that each got.

#25 [Bugfix] Made the status card 1:1 ratio
  lib/screens/shared/media/components/poster_image.dart
  lib/widgets/shared/status_card.dart
Labels: bug

#23 Create AltStore repository
  altstore.json
Labels: documentation

#34 Added 'Add to AltStore' button to README
  README.md
Labels: documentation

#38 Fixed typo in Readme
  README.md
Labels: documentation

#58 feature: Add new home carousel
  lib/l10n/app_en.arb
  lib/l10n/l10n_errors.txt
  lib/models/settings/client_settings_model.dart
  lib/models/settings/client_settings_model.freezed.dart
  lib/models/settings/client_settings_model.g.dart
  lib/screens/dashboard/dashboard_screen.dart
  lib/screens/dashboard/top_posters_row.dart
  lib/screens/settings/client_settings_page.dart
  lib/screens/settings/settings_scaffold.dart
  lib/screens/shared/media/carousel_banner.dart
  lib/screens/shared/media/media_banner.dart
  lib/widgets/shared/fladder_carousel.dart
Labels: enhancement

#80 feature(Desktop: Added seek indicator
  lib/screens/video_player/components/video_player_seek_indicator.dart
  lib/screens/video_player/video_player_controls.dart
Labels: enhancement
